services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: alumnodb
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: si1
    ports:
      - "9999:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1_schema.sql:ro
      - ./populate.sql:/docker-entrypoint-initdb.d/2_populate.sql:ro
      - ./actualiza.sql:/docker-entrypoint-initdb.d/3_actualiza.sql:ro
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alumnodb -d si1"]
      interval: 3s
      timeout: 3s
      retries: 20

  users:
    build:
      context: .
      dockerfile: Dockerfile.user
    environment:
      DATABASE_URL: postgresql+asyncpg://alumnodb:1234@db:5432/si1
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5050:5050"

  catalog:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      DATABASE_URL: postgresql+asyncpg://alumnodb:1234@db:5432/si1
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5051:5051"

volumes:
  db_data: